"""Add cascade delete to decks

Revision ID: bc36d46e26de
Revises: 4ce256a1fa91
Create Date: 2021-09-06 17:41:59.343251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc36d46e26de'
down_revision = '4ce256a1fa91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decks_owner_id_fkey', 'decks', type_='foreignkey')
    op.create_foreign_key(None, 'decks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.create_foreign_key('decks_owner_id_fkey', 'decks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
